# Project identification
sonar.projectKey=christianalejandro9803_control-calidad-software
sonar.organization=christianalejandro9803
sonar.host.url=https://sonarcloud.io

# Code sources
sonar.sources=app

# Optional: You can set the version of Python
sonar.python.version=3.12

# Tests (if any)
sonar.tests=tests
