# Identificación del proyecto en SonarCloud
sonar.projectKey=christianalejandro9803_control-calidad-software
sonar.organization=christianalejandro9803

# URL de SonarCloud
sonar.host.url=https://sonarcloud.io

# Nombre del proyecto
sonar.projectName=Control Calidad Software

# Descripción del proyecto (opcional)
sonar.projectDescription=Proyecto de control de calidad para la aplicación de software

# Definición de las carpetas con el código fuente
sonar.sources=app

# Definición de las carpetas donde están las pruebas
sonar.tests=tests

# Versión de Python utilizada
sonar.python.version=3.12

# Configuración para los archivos que deben ser excluidos (opcional)
sonar.exclusions=**/tests/**, **/migrations/**
