sonar.projectKey=christianalejandro9803_control-calidad-software
sonar.organization=christianalejandro9803
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=tests
sonar.python.version=3.12
